### PR TITLE
WIP: README.md tweaks

### LINKED ISSUE #8: Refine README
* Tweaking markdown to put the travisci badges in a table. 
* Fix typos
* Adding hyperlinks to FreeCAD project
* Refining the Quickstart section to offer the option of using `git clone` as a way to quickly update the workbench code if it's been modified upstream
* grammar

Note: your CLA is extensive and I'd rather not share all those personal details. I don't need any attribution for my contribution so I propose that you cherrypick the commit (will erase any of my info) and merge the code as your own. You can use this ticket as my authorization to do so.

### PR DESCRIPTION
**Pull request by luzpaz**
- [ ] Consider suggestions for default branch

Closes #8

### CODE REVIEW

**Comment by luzpaz** [comment]
As mentioned in #8  
```
Note: your CLA is extensive and I'd rather not share all those personal details. I don't need any attribution for my contribution so I propose that you cherrypick the commit (will erase any of my info) and merge the code as your own. You can use this ticket as my authorization to do so.
```

Also to preview the PR check out https://github.com/luzpaz/VirtualSatellite4-FreeCAD-mod/blob/README-tweaks/README.md

**Comment by PhilMFischer** [comment]
Thank you for your input. We still have quite Abit work to do to provide the first serious release. We will take your notes into account. I leave the PR open until then.

**Comment by luzpaz** [comment]
@PhilMFischer why not add section to the top of the README like so:

## Project Status 

Currently this FreeCAD module is in **Alpha** status. Feel free to test and open a ticket in this repository's [issue queue](https://github.com/virtualsatellite/VirtualSatellite4-FreeCAD-mod/issues).

**Comment by luzpaz** [comment]
@PhilMFischer Please when convenient, let me know. I'd like to share this project with the FreeCAD community. Perhaps when you feel it's ready for testing, would you mind posting on the [FreeCAD User Showcase forum](https://forum.freecadweb.org/viewforum.php?f=24) ?

**Comment by PhilMFischer** [comment]
@luzpaz Thanks for your further comments. As soon as we continue working on this topic, I will take them into account.

Yes, We are happy to keep you informed. As soon as we have the first reliable version ready, it would be great to share it with the FreeCAD community.

**Comment by PhilMFischer** [comment]
Your suggestions got considered in PR #16. Thank you!

**Pull request closed without merging**
